### ISSUE TITLE
Problem with Pubkey "y" coordinates recalculation

### ISSUE THREAD

**Issue by kamakuba** [johndoe31415/toyecc#7] opened 2021-01-24 16:11 UTC
Trying to recalculate "y" coordinates of public key, based on "x" coordinate.
```
#!/usr/bin/python3

from ecc import getcurvebyname, FieldElement, ECPrivateKey

curve = getcurvebyname("curve25519")
privatekey = ECPrivateKey(0x123456, curve)

print ('pubkey x: ', hex(int(privatekey.pubkey.point.x)))
print ('pubkey y: ', hex(int(privatekey.pubkey.point.y)))

x=int(privatekey.pubkey.point.x)

#  curve25519:  y^2 = x^3 + 486662*x^2 + x
y=hex(int(FieldElement(x**3+int(curve.a)*x**2+x, curve.p).sqrt()[0]))

print ('Recalculated y: ', y)
```

Obtain wrong result
```
pubkey x:  0x3a1754b57f5b66eaca28bf5d006f93eb287ba3f9535827ce318170c5394ffdc4
pubkey y:  0x6f7d0cc67331d815d0c8e05299ddab3afa0ba248048ccd3b37a66e5c6a2a32fb
Recalculated y:  0x1082f3398cce27ea2f371fad662254c505f45db7fb7332c4c85991a395d5ccf2
```

**Comment by johndoe31415** [comment] 2021-01-24 16:15
An Elliptic Curve is symmetric to the X axis, as can be easily seen by the form y²=.... This means for any given X coordinate, there can be up to two points on the Y axis. To recover Y uniquely, you need the X coordinate and the *sign* of the point.

You arbitrarily chose one coordinate after pulling the square root (sqrt()[0]) when in your case, sqrt()[1] would have been the correct one.

Not a bug, closing.

**Closed as completed by johndoe31415** 2021-01-24 16:15 UTC

**Comment by kamakuba** [comment] 2021-01-24 16:22
Thank you for explaining!
